Added @SapirLastimoza-Dooley to README contributors
makepath/xarray-spatial pull request #174
Opened 2021-01-12 16:22 UTC by SapirLastimoza-Dooley

2021-01-15 12:20 UTC, thuydotm requested changes

2021-01-15 12:20 UTC, thuydotm commented on xrspatial/aspect.py
> +        Numpy, CuPy, Dask, or CuPy GPU data array with agg.data = elevation
The explanation for param `agg` and the return of the function should be more clear. Ex: agg: xarray.DataArray. The data dimension of input aggregate is 2D and can be either a numpy array, a cupy array, a dask array with numpy backed or a dask array with cupy backed...

2021-01-15 12:20 UTC, thuydotm commented on xrspatial/aspect.py
> +        Numpy, CuPy, Dask, or CuPy GPU data array with agg.out = aspect
You may want to add some more details here. The output is a DataArray where its data dimension is the calculated aspect. Output data has the same type as of input. If we pass a DataArray with numpy-backed xarray, the output is also numpy-backed. Similarly with other input types.  Other attributes of the output aggregate are preserved as of input. Note that we don't have `.out` attribute in a DataArray.

2021-01-15 12:20 UTC, thuydotm commented on xrspatial/aspect.py
> +    <xarray.DataArray (dim_0: 3, dim_1: 3)>
Would be great if we specify the dimensions here then we can show that the coords of input and output are the same. Ex:
```
    agg = xr.DataArray(np.array([[0, 1, 0, 0],
                                 [1, 1, 0, 0],
                                 [0, 1, 2, 2],
                                 [1, 0, 2, 0],
                                 [0, 2, 2, 2]]),
                       dims=['lat', 'lon'])

    height, width = agg.shape
    _lon = np.linspace(0, width - 1, width)
    _lat = np.linspace(0, height - 1, height)
    agg['lon'] = _lon
    agg['lat'] = _lat
```

2021-01-15 12:20 UTC, thuydotm commented on .vscode/settings.json
> +{
Can you remove the .vscode folder from this PR? 
You can still keep it in your local repo `echo ".vscode/" >> .gitignore`

2021-02-26 16:08 UTC, brendancol commented
@SapirLastimoza-Dooley this is looking great!  Let me know when you think its good to merge and we'll merge it.

2021-03-20 17:05 UTC, thuydotm commented
@SapirLastimoza-Dooley Everything looks good to me except for a typo with pd.DataFrame. Can you please fix this and we'll be good to merge.

2021-03-22 16:32 UTC, merged