zonal crosstab: speedup numpy case
makepath/xarray-spatial pull request #586
Opened 2021-11-26 09:52 UTC by thuydotm

2021-11-29 13:25 UTC, ianthomas23 requested changes

2021-11-29 13:25 UTC, ianthomas23 commented on xrspatial/zonal.py
> +        result = values.flatten()[sorted_indices]
Would it be better to use `ravel` here, which only copies if necessary, rather than `flatten` which always copies?

2021-11-29 13:25 UTC, ianthomas23 commented on xrspatial/zonal.py
> +            result[i] = values[i].flatten()[sorted_indices]
Same question about `ravel` vs `flatten`.

2021-11-29 13:25 UTC, ianthomas23 commented on xrspatial/zonal.py
> +    # remove zones that does not exist in `zones` raster
`does` should be `do`.

2021-11-29 13:25 UTC, ianthomas23 commented on xrspatial/zonal.py
> +    zone_ids = [z for z in zone_ids if z in unique_zones]
Could this be in an `else` block of the previous `if` statement? (Like first review comment).

2021-11-29 13:25 UTC, ianthomas23 commented on xrspatial/zonal.py
> +    flatten_zones = zones.flatten()
`ravel` rather than `flatten` to only copy if necessary?

2021-12-06 08:50 UTC, merged

2021-12-06 08:51 UTC, thuydotm commented
Changed as suggested. Thanks @ianthomas23!